apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: gitlab-database
  namespace: gitlab

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: SecretStore

  target:
    name: gitlab-database-secret
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: gitlab/prod/database